set character_set_client = utf8;
set character_set_server = utf8;
set character_set_connection = utf8;
set character_set_results = utf8;
set character_set_database = utf8;
/*!40014 SET SESSION FOREIGN_KEY_CHECKS=0 */;
select 'Creating tables...' as ' ';
source allergy.sql;
source allergy_reaction.sql;
source buendia_obs_sync_map.sql;
source buendia_order_sync_map.sql;
source buendia_patient_sync_map.sql;
source care_setting.sql;
source clob_datatype_storage.sql;
source cohort.sql;
source cohort_member.sql;
source concept.sql;
source concept_answer.sql;
source concept_attribute.sql;
source concept_attribute_type.sql;
source concept_class.sql;
source concept_complex.sql;
source concept_datatype.sql;
source concept_description.sql;
source concept_map_type.sql;
source concept_name.sql;
source concept_name_tag.sql;
source concept_name_tag_map.sql;
source concept_numeric.sql;
source concept_proposal.sql;
source concept_proposal_tag_map.sql;
source concept_reference_map.sql;
source concept_reference_source.sql;
source concept_reference_term.sql;
source concept_reference_term_map.sql;
source concept_set.sql;
source concept_state_conversion.sql;
source concept_stop_word.sql;
source conditions.sql;
source drug.sql;
source drug_ingredient.sql;
source drug_order.sql;
source drug_reference_map.sql;
source encounter.sql;
source encounter_diagnosis.sql;
source encounter_provider.sql;
source encounter_role.sql;
source encounter_type.sql;
source field.sql;
source field_answer.sql;
source field_type.sql;
source form.sql;
source form_field.sql;
source form_resource.sql;
source global_property.sql;
source hl7_in_archive.sql;
source hl7_in_error.sql;
source hl7_in_queue.sql;
source hl7_source.sql;
source liquibasechangelog.sql;
source liquibasechangeloglock.sql;
source location.sql;
source location_attribute.sql;
source location_attribute_type.sql;
source location_tag.sql;
source location_tag_map.sql;
source logic_rule_definition.sql;
source logic_rule_token.sql;
source logic_rule_token_tag.sql;
source logic_token_registration.sql;
source logic_token_registration_tag.sql;
source note.sql;
source notification_alert.sql;
source notification_alert_recipient.sql;
source notification_template.sql;
source obs.sql;
source order_frequency.sql;
source order_group.sql;
source order_set.sql;
source order_set_member.sql;
source order_type.sql;
source order_type_class_map.sql;
source orders.sql;
source patient.sql;
source patient_identifier.sql;
source patient_identifier_type.sql;
source patient_program.sql;
source patient_program_attribute.sql;
source patient_state.sql;
source person.sql;
source person_address.sql;
source person_attribute.sql;
source person_attribute_type.sql;
source person_merge_log.sql;
source person_name.sql;
source privilege.sql;
source program.sql;
source program_attribute_type.sql;
source program_workflow.sql;
source program_workflow_state.sql;
source provider.sql;
source provider_attribute.sql;
source provider_attribute_type.sql;
source relationship.sql;
source relationship_type.sql;
source report_object.sql;
source report_schema_xml.sql;
source role.sql;
source role_privilege.sql;
source role_role.sql;
source scheduler_task_config.sql;
source scheduler_task_config_property.sql;
source serialized_object.sql;
source test_order.sql;
source user_property.sql;
source user_role.sql;
source users.sql;
source visit.sql;
source visit_attribute.sql;
source visit_attribute_type.sql;
source visit_type.sql;
select 'Loading allergy.txt...' as ' ';
lock tables allergy write;
load data local infile 'allergy.txt' into table allergy character set utf8;
unlock tables;
select 'Loading allergy_reaction.txt...' as ' ';
lock tables allergy_reaction write;
load data local infile 'allergy_reaction.txt' into table allergy_reaction character set utf8;
unlock tables;
select 'Loading buendia_obs_sync_map.txt...' as ' ';
lock tables buendia_obs_sync_map write;
load data local infile 'buendia_obs_sync_map.txt' into table buendia_obs_sync_map character set utf8;
unlock tables;
select 'Loading buendia_order_sync_map.txt...' as ' ';
lock tables buendia_order_sync_map write;
load data local infile 'buendia_order_sync_map.txt' into table buendia_order_sync_map character set utf8;
unlock tables;
select 'Loading buendia_patient_sync_map.txt...' as ' ';
lock tables buendia_patient_sync_map write;
load data local infile 'buendia_patient_sync_map.txt' into table buendia_patient_sync_map character set utf8;
unlock tables;
select 'Loading care_setting.txt...' as ' ';
lock tables care_setting write;
load data local infile 'care_setting.txt' into table care_setting character set utf8;
unlock tables;
select 'Loading clob_datatype_storage.txt...' as ' ';
lock tables clob_datatype_storage write;
load data local infile 'clob_datatype_storage.txt' into table clob_datatype_storage character set utf8;
unlock tables;
select 'Loading cohort.txt...' as ' ';
lock tables cohort write;
load data local infile 'cohort.txt' into table cohort character set utf8;
unlock tables;
select 'Loading cohort_member.txt...' as ' ';
lock tables cohort_member write;
load data local infile 'cohort_member.txt' into table cohort_member character set utf8;
unlock tables;
select 'Loading concept.txt...' as ' ';
lock tables concept write;
load data local infile 'concept.txt' into table concept character set utf8;
unlock tables;
select 'Loading concept_answer.txt...' as ' ';
lock tables concept_answer write;
load data local infile 'concept_answer.txt' into table concept_answer character set utf8;
unlock tables;
select 'Loading concept_attribute.txt...' as ' ';
lock tables concept_attribute write;
load data local infile 'concept_attribute.txt' into table concept_attribute character set utf8;
unlock tables;
select 'Loading concept_attribute_type.txt...' as ' ';
lock tables concept_attribute_type write;
load data local infile 'concept_attribute_type.txt' into table concept_attribute_type character set utf8;
unlock tables;
select 'Loading concept_class.txt...' as ' ';
lock tables concept_class write;
load data local infile 'concept_class.txt' into table concept_class character set utf8;
unlock tables;
select 'Loading concept_complex.txt...' as ' ';
lock tables concept_complex write;
load data local infile 'concept_complex.txt' into table concept_complex character set utf8;
unlock tables;
select 'Loading concept_datatype.txt...' as ' ';
lock tables concept_datatype write;
load data local infile 'concept_datatype.txt' into table concept_datatype character set utf8;
unlock tables;
select 'Loading concept_description.txt...' as ' ';
lock tables concept_description write;
load data local infile 'concept_description.txt' into table concept_description character set utf8;
unlock tables;
select 'Loading concept_map_type.txt...' as ' ';
lock tables concept_map_type write;
load data local infile 'concept_map_type.txt' into table concept_map_type character set utf8;
unlock tables;
select 'Loading concept_name.txt...' as ' ';
lock tables concept_name write;
load data local infile 'concept_name.txt' into table concept_name character set utf8;
unlock tables;
select 'Loading concept_name_tag.txt...' as ' ';
lock tables concept_name_tag write;
load data local infile 'concept_name_tag.txt' into table concept_name_tag character set utf8;
unlock tables;
select 'Loading concept_name_tag_map.txt...' as ' ';
lock tables concept_name_tag_map write;
load data local infile 'concept_name_tag_map.txt' into table concept_name_tag_map character set utf8;
unlock tables;
select 'Loading concept_numeric.txt...' as ' ';
lock tables concept_numeric write;
load data local infile 'concept_numeric.txt' into table concept_numeric character set utf8;
unlock tables;
select 'Loading concept_proposal.txt...' as ' ';
lock tables concept_proposal write;
load data local infile 'concept_proposal.txt' into table concept_proposal character set utf8;
unlock tables;
select 'Loading concept_proposal_tag_map.txt...' as ' ';
lock tables concept_proposal_tag_map write;
load data local infile 'concept_proposal_tag_map.txt' into table concept_proposal_tag_map character set utf8;
unlock tables;
select 'Loading concept_reference_map.txt...' as ' ';
lock tables concept_reference_map write;
load data local infile 'concept_reference_map.txt' into table concept_reference_map character set utf8;
unlock tables;
select 'Loading concept_reference_source.txt...' as ' ';
lock tables concept_reference_source write;
load data local infile 'concept_reference_source.txt' into table concept_reference_source character set utf8;
unlock tables;
select 'Loading concept_reference_term.txt...' as ' ';
lock tables concept_reference_term write;
load data local infile 'concept_reference_term.txt' into table concept_reference_term character set utf8;
unlock tables;
select 'Loading concept_reference_term_map.txt...' as ' ';
lock tables concept_reference_term_map write;
load data local infile 'concept_reference_term_map.txt' into table concept_reference_term_map character set utf8;
unlock tables;
select 'Loading concept_set.txt...' as ' ';
lock tables concept_set write;
load data local infile 'concept_set.txt' into table concept_set character set utf8;
unlock tables;
select 'Loading concept_state_conversion.txt...' as ' ';
lock tables concept_state_conversion write;
load data local infile 'concept_state_conversion.txt' into table concept_state_conversion character set utf8;
unlock tables;
select 'Loading concept_stop_word.txt...' as ' ';
lock tables concept_stop_word write;
load data local infile 'concept_stop_word.txt' into table concept_stop_word character set utf8;
unlock tables;
select 'Loading conditions.txt...' as ' ';
lock tables conditions write;
load data local infile 'conditions.txt' into table conditions character set utf8;
unlock tables;
select 'Loading drug.txt...' as ' ';
lock tables drug write;
load data local infile 'drug.txt' into table drug character set utf8;
unlock tables;
select 'Loading drug_ingredient.txt...' as ' ';
lock tables drug_ingredient write;
load data local infile 'drug_ingredient.txt' into table drug_ingredient character set utf8;
unlock tables;
select 'Loading drug_order.txt...' as ' ';
lock tables drug_order write;
load data local infile 'drug_order.txt' into table drug_order character set utf8;
unlock tables;
select 'Loading drug_reference_map.txt...' as ' ';
lock tables drug_reference_map write;
load data local infile 'drug_reference_map.txt' into table drug_reference_map character set utf8;
unlock tables;
select 'Loading encounter.txt...' as ' ';
lock tables encounter write;
load data local infile 'encounter.txt' into table encounter character set utf8;
unlock tables;
select 'Loading encounter_diagnosis.txt...' as ' ';
lock tables encounter_diagnosis write;
load data local infile 'encounter_diagnosis.txt' into table encounter_diagnosis character set utf8;
unlock tables;
select 'Loading encounter_provider.txt...' as ' ';
lock tables encounter_provider write;
load data local infile 'encounter_provider.txt' into table encounter_provider character set utf8;
unlock tables;
select 'Loading encounter_role.txt...' as ' ';
lock tables encounter_role write;
load data local infile 'encounter_role.txt' into table encounter_role character set utf8;
unlock tables;
select 'Loading encounter_type.txt...' as ' ';
lock tables encounter_type write;
load data local infile 'encounter_type.txt' into table encounter_type character set utf8;
unlock tables;
select 'Loading field.txt...' as ' ';
lock tables field write;
load data local infile 'field.txt' into table field character set utf8;
unlock tables;
select 'Loading field_answer.txt...' as ' ';
lock tables field_answer write;
load data local infile 'field_answer.txt' into table field_answer character set utf8;
unlock tables;
select 'Loading field_type.txt...' as ' ';
lock tables field_type write;
load data local infile 'field_type.txt' into table field_type character set utf8;
unlock tables;
select 'Loading form.txt...' as ' ';
lock tables form write;
load data local infile 'form.txt' into table form character set utf8;
unlock tables;
select 'Loading form_field.txt...' as ' ';
lock tables form_field write;
load data local infile 'form_field.txt' into table form_field character set utf8;
unlock tables;
select 'Loading form_resource.txt...' as ' ';
lock tables form_resource write;
load data local infile 'form_resource.txt' into table form_resource character set utf8;
unlock tables;
select 'Loading global_property.txt...' as ' ';
lock tables global_property write;
load data local infile 'global_property.txt' into table global_property character set utf8;
unlock tables;
select 'Loading hl7_in_archive.txt...' as ' ';
lock tables hl7_in_archive write;
load data local infile 'hl7_in_archive.txt' into table hl7_in_archive character set utf8;
unlock tables;
select 'Loading hl7_in_error.txt...' as ' ';
lock tables hl7_in_error write;
load data local infile 'hl7_in_error.txt' into table hl7_in_error character set utf8;
unlock tables;
select 'Loading hl7_in_queue.txt...' as ' ';
lock tables hl7_in_queue write;
load data local infile 'hl7_in_queue.txt' into table hl7_in_queue character set utf8;
unlock tables;
select 'Loading hl7_source.txt...' as ' ';
lock tables hl7_source write;
load data local infile 'hl7_source.txt' into table hl7_source character set utf8;
unlock tables;
select 'Loading liquibasechangelog.txt...' as ' ';
lock tables liquibasechangelog write;
load data local infile 'liquibasechangelog.txt' into table liquibasechangelog character set utf8;
unlock tables;
select 'Loading liquibasechangeloglock.txt...' as ' ';
lock tables liquibasechangeloglock write;
load data local infile 'liquibasechangeloglock.txt' into table liquibasechangeloglock character set utf8;
unlock tables;
select 'Loading location.txt...' as ' ';
lock tables location write;
load data local infile 'location.txt' into table location character set utf8;
unlock tables;
select 'Loading location_attribute.txt...' as ' ';
lock tables location_attribute write;
load data local infile 'location_attribute.txt' into table location_attribute character set utf8;
unlock tables;
select 'Loading location_attribute_type.txt...' as ' ';
lock tables location_attribute_type write;
load data local infile 'location_attribute_type.txt' into table location_attribute_type character set utf8;
unlock tables;
select 'Loading location_tag.txt...' as ' ';
lock tables location_tag write;
load data local infile 'location_tag.txt' into table location_tag character set utf8;
unlock tables;
select 'Loading location_tag_map.txt...' as ' ';
lock tables location_tag_map write;
load data local infile 'location_tag_map.txt' into table location_tag_map character set utf8;
unlock tables;
select 'Loading logic_rule_definition.txt...' as ' ';
lock tables logic_rule_definition write;
load data local infile 'logic_rule_definition.txt' into table logic_rule_definition character set utf8;
unlock tables;
select 'Loading logic_rule_token.txt...' as ' ';
lock tables logic_rule_token write;
load data local infile 'logic_rule_token.txt' into table logic_rule_token character set utf8;
unlock tables;
select 'Loading logic_rule_token_tag.txt...' as ' ';
lock tables logic_rule_token_tag write;
load data local infile 'logic_rule_token_tag.txt' into table logic_rule_token_tag character set utf8;
unlock tables;
select 'Loading logic_token_registration.txt...' as ' ';
lock tables logic_token_registration write;
load data local infile 'logic_token_registration.txt' into table logic_token_registration character set utf8;
unlock tables;
select 'Loading logic_token_registration_tag.txt...' as ' ';
lock tables logic_token_registration_tag write;
load data local infile 'logic_token_registration_tag.txt' into table logic_token_registration_tag character set utf8;
unlock tables;
select 'Loading note.txt...' as ' ';
lock tables note write;
load data local infile 'note.txt' into table note character set utf8;
unlock tables;
select 'Loading notification_alert.txt...' as ' ';
lock tables notification_alert write;
load data local infile 'notification_alert.txt' into table notification_alert character set utf8;
unlock tables;
select 'Loading notification_alert_recipient.txt...' as ' ';
lock tables notification_alert_recipient write;
load data local infile 'notification_alert_recipient.txt' into table notification_alert_recipient character set utf8;
unlock tables;
select 'Loading notification_template.txt...' as ' ';
lock tables notification_template write;
load data local infile 'notification_template.txt' into table notification_template character set utf8;
unlock tables;
select 'Loading obs.txt...' as ' ';
lock tables obs write;
load data local infile 'obs.txt' into table obs character set utf8;
unlock tables;
select 'Loading order_frequency.txt...' as ' ';
lock tables order_frequency write;
load data local infile 'order_frequency.txt' into table order_frequency character set utf8;
unlock tables;
select 'Loading order_group.txt...' as ' ';
lock tables order_group write;
load data local infile 'order_group.txt' into table order_group character set utf8;
unlock tables;
select 'Loading order_set.txt...' as ' ';
lock tables order_set write;
load data local infile 'order_set.txt' into table order_set character set utf8;
unlock tables;
select 'Loading order_set_member.txt...' as ' ';
lock tables order_set_member write;
load data local infile 'order_set_member.txt' into table order_set_member character set utf8;
unlock tables;
select 'Loading order_type.txt...' as ' ';
lock tables order_type write;
load data local infile 'order_type.txt' into table order_type character set utf8;
unlock tables;
select 'Loading order_type_class_map.txt...' as ' ';
lock tables order_type_class_map write;
load data local infile 'order_type_class_map.txt' into table order_type_class_map character set utf8;
unlock tables;
select 'Loading orders.txt...' as ' ';
lock tables orders write;
load data local infile 'orders.txt' into table orders character set utf8;
unlock tables;
select 'Loading patient.txt...' as ' ';
lock tables patient write;
load data local infile 'patient.txt' into table patient character set utf8;
unlock tables;
select 'Loading patient_identifier.txt...' as ' ';
lock tables patient_identifier write;
load data local infile 'patient_identifier.txt' into table patient_identifier character set utf8;
unlock tables;
select 'Loading patient_identifier_type.txt...' as ' ';
lock tables patient_identifier_type write;
load data local infile 'patient_identifier_type.txt' into table patient_identifier_type character set utf8;
unlock tables;
select 'Loading patient_program.txt...' as ' ';
lock tables patient_program write;
load data local infile 'patient_program.txt' into table patient_program character set utf8;
unlock tables;
select 'Loading patient_program_attribute.txt...' as ' ';
lock tables patient_program_attribute write;
load data local infile 'patient_program_attribute.txt' into table patient_program_attribute character set utf8;
unlock tables;
select 'Loading patient_state.txt...' as ' ';
lock tables patient_state write;
load data local infile 'patient_state.txt' into table patient_state character set utf8;
unlock tables;
select 'Loading person.txt...' as ' ';
lock tables person write;
load data local infile 'person.txt' into table person character set utf8;
unlock tables;
select 'Loading person_address.txt...' as ' ';
lock tables person_address write;
load data local infile 'person_address.txt' into table person_address character set utf8;
unlock tables;
select 'Loading person_attribute.txt...' as ' ';
lock tables person_attribute write;
load data local infile 'person_attribute.txt' into table person_attribute character set utf8;
unlock tables;
select 'Loading person_attribute_type.txt...' as ' ';
lock tables person_attribute_type write;
load data local infile 'person_attribute_type.txt' into table person_attribute_type character set utf8;
unlock tables;
select 'Loading person_merge_log.txt...' as ' ';
lock tables person_merge_log write;
load data local infile 'person_merge_log.txt' into table person_merge_log character set utf8;
unlock tables;
select 'Loading person_name.txt...' as ' ';
lock tables person_name write;
load data local infile 'person_name.txt' into table person_name character set utf8;
unlock tables;
select 'Loading privilege.txt...' as ' ';
lock tables privilege write;
load data local infile 'privilege.txt' into table privilege character set utf8;
unlock tables;
select 'Loading program.txt...' as ' ';
lock tables program write;
load data local infile 'program.txt' into table program character set utf8;
unlock tables;
select 'Loading program_attribute_type.txt...' as ' ';
lock tables program_attribute_type write;
load data local infile 'program_attribute_type.txt' into table program_attribute_type character set utf8;
unlock tables;
select 'Loading program_workflow.txt...' as ' ';
lock tables program_workflow write;
load data local infile 'program_workflow.txt' into table program_workflow character set utf8;
unlock tables;
select 'Loading program_workflow_state.txt...' as ' ';
lock tables program_workflow_state write;
load data local infile 'program_workflow_state.txt' into table program_workflow_state character set utf8;
unlock tables;
select 'Loading provider.txt...' as ' ';
lock tables provider write;
load data local infile 'provider.txt' into table provider character set utf8;
unlock tables;
select 'Loading provider_attribute.txt...' as ' ';
lock tables provider_attribute write;
load data local infile 'provider_attribute.txt' into table provider_attribute character set utf8;
unlock tables;
select 'Loading provider_attribute_type.txt...' as ' ';
lock tables provider_attribute_type write;
load data local infile 'provider_attribute_type.txt' into table provider_attribute_type character set utf8;
unlock tables;
select 'Loading relationship.txt...' as ' ';
lock tables relationship write;
load data local infile 'relationship.txt' into table relationship character set utf8;
unlock tables;
select 'Loading relationship_type.txt...' as ' ';
lock tables relationship_type write;
load data local infile 'relationship_type.txt' into table relationship_type character set utf8;
unlock tables;
select 'Loading report_object.txt...' as ' ';
lock tables report_object write;
load data local infile 'report_object.txt' into table report_object character set utf8;
unlock tables;
select 'Loading report_schema_xml.txt...' as ' ';
lock tables report_schema_xml write;
load data local infile 'report_schema_xml.txt' into table report_schema_xml character set utf8;
unlock tables;
select 'Loading role.txt...' as ' ';
lock tables role write;
load data local infile 'role.txt' into table role character set utf8;
unlock tables;
select 'Loading role_privilege.txt...' as ' ';
lock tables role_privilege write;
load data local infile 'role_privilege.txt' into table role_privilege character set utf8;
unlock tables;
select 'Loading role_role.txt...' as ' ';
lock tables role_role write;
load data local infile 'role_role.txt' into table role_role character set utf8;
unlock tables;
select 'Loading scheduler_task_config.txt...' as ' ';
lock tables scheduler_task_config write;
load data local infile 'scheduler_task_config.txt' into table scheduler_task_config character set utf8;
unlock tables;
select 'Loading scheduler_task_config_property.txt...' as ' ';
lock tables scheduler_task_config_property write;
load data local infile 'scheduler_task_config_property.txt' into table scheduler_task_config_property character set utf8;
unlock tables;
select 'Loading serialized_object.txt...' as ' ';
lock tables serialized_object write;
load data local infile 'serialized_object.txt' into table serialized_object character set utf8;
unlock tables;
select 'Loading test_order.txt...' as ' ';
lock tables test_order write;
load data local infile 'test_order.txt' into table test_order character set utf8;
unlock tables;
select 'Loading user_property.txt...' as ' ';
lock tables user_property write;
load data local infile 'user_property.txt' into table user_property character set utf8;
unlock tables;
select 'Loading user_role.txt...' as ' ';
lock tables user_role write;
load data local infile 'user_role.txt' into table user_role character set utf8;
unlock tables;
select 'Loading users.txt...' as ' ';
lock tables users write;
load data local infile 'users.txt' into table users character set utf8;
unlock tables;
select 'Loading visit.txt...' as ' ';
lock tables visit write;
load data local infile 'visit.txt' into table visit character set utf8;
unlock tables;
select 'Loading visit_attribute.txt...' as ' ';
lock tables visit_attribute write;
load data local infile 'visit_attribute.txt' into table visit_attribute character set utf8;
unlock tables;
select 'Loading visit_attribute_type.txt...' as ' ';
lock tables visit_attribute_type write;
load data local infile 'visit_attribute_type.txt' into table visit_attribute_type character set utf8;
unlock tables;
select 'Loading visit_type.txt...' as ' ';
lock tables visit_type write;
load data local infile 'visit_type.txt' into table visit_type character set utf8;
unlock tables;
select 'Done.' as ' ';
